// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221117004828_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.BuscaEspecialidade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("Especialidadeid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("criado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_especialidade")
                        .HasColumnType("integer");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Especialidadeid");

                    b.ToTable("busca_especialidade");
                });

            modelBuilder.Entity("Data.Entities.Especialidade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("criado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("id_especialidade")
                        .HasColumnType("integer");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("id_especialidade");

                    b.ToTable("especialidade");
                });

            modelBuilder.Entity("Data.Entities.Especialidade_Medico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("criado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_especialidade")
                        .HasColumnType("integer");

                    b.Property<int>("id_medico")
                        .HasColumnType("integer");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Especialidade_Medico");
                });

            modelBuilder.Entity("Data.Entities.Medico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("criado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("crm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("estado_crm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("id_medico")
                        .HasColumnType("integer");

                    b.Property<int?>("id_medidco")
                        .HasColumnType("integer");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("id_medico");

                    b.HasIndex("id_medidco");

                    b.ToTable("medico");
                });

            modelBuilder.Entity("Data.Entities.Perfil", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("criado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("perfil");
                });

            modelBuilder.Entity("Data.Entities.Plantao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("Especialidadesid")
                        .HasColumnType("integer");

                    b.Property<int>("Medicosid")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadeSaudesid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("criado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("dia_semana")
                        .HasColumnType("integer");

                    b.Property<DateTime>("editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("horariofim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("horarioinicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_especialidade")
                        .HasColumnType("integer");

                    b.Property<int>("id_medico")
                        .HasColumnType("integer");

                    b.Property<int>("id_unidade")
                        .HasColumnType("integer");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Especialidadesid");

                    b.HasIndex("Medicosid");

                    b.HasIndex("UnidadeSaudesid");

                    b.ToTable("plantao");
                });

            modelBuilder.Entity("Data.Entities.UnidadeSaude", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("criado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("id_unidade")
                        .HasColumnType("integer");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("id_unidade");

                    b.ToTable("unidade_saude");
                });

            modelBuilder.Entity("Data.Entities.UnidadeSaudeMedico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("criado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_medidco")
                        .HasColumnType("integer");

                    b.Property<int>("id_unidade")
                        .HasColumnType("integer");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("UnidadeSaudeMedico");
                });

            modelBuilder.Entity("Data.Entities.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("criado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_perfil")
                        .HasColumnType("integer");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("sexo")
                        .HasColumnType("character(1)");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("id_perfil");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("Data.Entities.BuscaEspecialidade", b =>
                {
                    b.HasOne("Data.Entities.Especialidade", "Especialidade")
                        .WithMany()
                        .HasForeignKey("Especialidadeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("Data.Entities.Especialidade", b =>
                {
                    b.HasOne("Data.Entities.Especialidade_Medico", null)
                        .WithMany("Especialidade")
                        .HasForeignKey("id_especialidade");
                });

            modelBuilder.Entity("Data.Entities.Medico", b =>
                {
                    b.HasOne("Data.Entities.Especialidade_Medico", null)
                        .WithMany("Medico")
                        .HasForeignKey("id_medico");

                    b.HasOne("Data.Entities.UnidadeSaudeMedico", null)
                        .WithMany("Medico")
                        .HasForeignKey("id_medidco");
                });

            modelBuilder.Entity("Data.Entities.Plantao", b =>
                {
                    b.HasOne("Data.Entities.Especialidade", "Especialidades")
                        .WithMany()
                        .HasForeignKey("Especialidadesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Medico", "Medicos")
                        .WithMany()
                        .HasForeignKey("Medicosid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.UnidadeSaude", "UnidadeSaudes")
                        .WithMany()
                        .HasForeignKey("UnidadeSaudesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidades");

                    b.Navigation("Medicos");

                    b.Navigation("UnidadeSaudes");
                });

            modelBuilder.Entity("Data.Entities.UnidadeSaude", b =>
                {
                    b.HasOne("Data.Entities.UnidadeSaudeMedico", null)
                        .WithMany("UnidadeSaude")
                        .HasForeignKey("id_unidade");
                });

            modelBuilder.Entity("Data.Entities.Usuario", b =>
                {
                    b.HasOne("Data.Entities.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("id_perfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Data.Entities.Especialidade_Medico", b =>
                {
                    b.Navigation("Especialidade");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("Data.Entities.UnidadeSaudeMedico", b =>
                {
                    b.Navigation("Medico");

                    b.Navigation("UnidadeSaude");
                });
#pragma warning restore 612, 618
        }
    }
}
