// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221127012447_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.BuscaEspecialidade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("criado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("editado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("id_especialidade")
                        .HasColumnType("integer");

                    b.Property<int?>("id_especialidade_be")
                        .HasColumnType("integer");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("id_especialidade");

                    b.HasIndex("id_especialidade_be");

                    b.ToTable("busca_especialidade");
                });

            modelBuilder.Entity("Data.Entities.Especialidade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("criado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("editado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("especialidade");
                });

            modelBuilder.Entity("Data.Entities.Medico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("criado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("crm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("editado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("estado_crm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("id_medico")
                        .HasColumnType("integer");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("id_medico");

                    b.ToTable("medico");
                });

            modelBuilder.Entity("Data.Entities.Perfil", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("criado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("editado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("perfil");
                });

            modelBuilder.Entity("Data.Entities.Plantao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("criado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("dia_semana")
                        .HasColumnType("integer");

                    b.Property<DateTime>("editado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("horariofim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("horarioinicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_especialidade")
                        .HasColumnType("integer");

                    b.Property<int>("id_medico")
                        .HasColumnType("integer");

                    b.Property<int?>("id_plantao")
                        .HasColumnType("integer");

                    b.Property<int>("id_unidade")
                        .HasColumnType("integer");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("id_especialidade");

                    b.HasIndex("id_medico");

                    b.HasIndex("id_plantao");

                    b.HasIndex("id_unidade");

                    b.ToTable("plantao");
                });

            modelBuilder.Entity("Data.Entities.UnidadeSaude", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("criado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("editado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("unidade_saude");
                });

            modelBuilder.Entity("Data.Entities.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("criado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("editado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_perfil")
                        .HasColumnType("integer");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("sexo")
                        .HasColumnType("character(1)");

                    b.Property<int>("situacao")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("id_perfil");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("EspecialidadeMedico", b =>
                {
                    b.Property<int>("id_especialidade")
                        .HasColumnType("integer");

                    b.Property<int>("id_medico")
                        .HasColumnType("integer");

                    b.HasKey("id_especialidade", "id_medico");

                    b.HasIndex("id_medico");

                    b.ToTable("EspecialidadeMedico");
                });

            modelBuilder.Entity("Data.Entities.BuscaEspecialidade", b =>
                {
                    b.HasOne("Data.Entities.Especialidade", "Especialidade")
                        .WithMany()
                        .HasForeignKey("id_especialidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Especialidade", null)
                        .WithMany("BuscaEspecialidades")
                        .HasForeignKey("id_especialidade_be");

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("Data.Entities.Medico", b =>
                {
                    b.HasOne("Data.Entities.UnidadeSaude", null)
                        .WithMany("Medicos")
                        .HasForeignKey("id_medico");
                });

            modelBuilder.Entity("Data.Entities.Plantao", b =>
                {
                    b.HasOne("Data.Entities.Especialidade", "Especialidades")
                        .WithMany()
                        .HasForeignKey("id_especialidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Medico", "Medicos")
                        .WithMany()
                        .HasForeignKey("id_medico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.UnidadeSaude", null)
                        .WithMany("Plantao")
                        .HasForeignKey("id_plantao");

                    b.HasOne("Data.Entities.UnidadeSaude", "UnidadeSaudes")
                        .WithMany()
                        .HasForeignKey("id_unidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidades");

                    b.Navigation("Medicos");

                    b.Navigation("UnidadeSaudes");
                });

            modelBuilder.Entity("Data.Entities.Usuario", b =>
                {
                    b.HasOne("Data.Entities.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("id_perfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("EspecialidadeMedico", b =>
                {
                    b.HasOne("Data.Entities.Especialidade", null)
                        .WithMany()
                        .HasForeignKey("id_especialidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Medico", null)
                        .WithMany()
                        .HasForeignKey("id_medico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.Especialidade", b =>
                {
                    b.Navigation("BuscaEspecialidades");
                });

            modelBuilder.Entity("Data.Entities.UnidadeSaude", b =>
                {
                    b.Navigation("Medicos");

                    b.Navigation("Plantao");
                });
#pragma warning restore 612, 618
        }
    }
}
